AUGMENTATION: True #Data augmentation is a technique used to artificially increase the size of the training dataset by applying transformations such as rotations, flips, zooming, cropping, brightness adjustments, etc.
IMAGE_SIZE: [224,224,3] #Resizes the image to 224x224
BATCH_SIZE: 16 #A batch size of 16 means that 16 images are passed through the network before the weights are updated.
INCLUDE_TOP: False #Avoids the fully connected layer
EPOCHS: 5
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01